### ISSUE TITLE
Type for opt_param and aug_param for visualize_filter function

### ISSUE THREAD

**Issue by eddiem3** [Sparkier/luna#11]
I'm trying to run the example in the readme...

`loss, image = featurevis.visualize_filter(image, model, "mixed6", 10, 200, 1)`

 but I'm getting this error...

`Traceback (most recent call last):
  File "/home/emassey3/development/luna/test.py", line 9, in <module>
    loss, image = featurevis.visualize_filter(image, model, "mixed6", 10, 200, 1)
  File "/home/emassey3/development/luna/luna/featurevis/featurevis.py", line 64, in visualize_filter
    for iteration in range(opt_param.iterations):
AttributeError: 'int' object has no attribute 'iterations'
`

What was the intended data type for opt_params in featurevis.py? I can't seem to find it anywhere else in the repo.

`def visualize_filter(image, model, layer, filter_index, opt_param, aug_param):`

**Comment by Sparkier** [comment]
Hey, sorry for the incomplete documentation on this. The type of opt_params should be as follows:
https://github.com/Sparkier/luna/blob/81d8d689b9d5a50175ab641f479a73f3782c1e3c/luna/featurevis/featurevis.py#L13-L22
So essentially you need an object holding the iterations and learning rate for the optimization.

**Comment by eddiem3** [comment]
Thanks! I didn't even notice that class. I submitted a pull request to update the readme example to use these classes.
