### ISSUE TITLE
Which kinds of models are/will be supported?

### ISSUE THREAD

**Issue by evanrmurphy** [Sparkier/luna#44]
Hi, is Luna only meant for vision models, or is/will it be designed for other kinds of ML models as well?

**Comment by Sparkier** [comment]
We are currently not planning to adapt this for anything that is not image based. Afaik, for other models, this approach has not yet shown similar success. Let me know if you had anything specific in mind.

**Comment by evanrmurphy** [comment]
Hi Sparkier, thanks for working on this library!

Well, it's not hard to imagine an analogous approach of "feature audiation" for audio-based models (speech recognition, audio classification, etc.) Things get a little more abstract perhaps with language models or reinforcement learning models, but those may be the most important kinds of models to study.

If tools don't exist for someone to study a particular model, how can success be demonstrated there? It's kind of a chicken-and-egg problem, I suppose.

**Comment by Sparkier** [comment]
I completely agree. If you would like to contribute to this library, you're most welcome. Sadly, we do currently not have the time to investigate different kinds of models. I have previously [experimented with language models](https://pair-code.github.io/interpretability/text-dream/explainable/), but with limited success.

**Comment by evanrmurphy** [comment]
Thanks for the discussion, I'm glad to know you share these views. And I didn't mean to put the burden of implementing all interpretability tooling onto you! I am writing an investigation about interpretability as a research direction now, but after that I'll probably get into direct interpretability research or working on tooling. Maybe then I can be a contributor to your library.
